name: Deploy Web
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build web --release
      - uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "build/web/"
          REMOTE_HOST: "server.4ft.me"
          REMOTE_USER: "root"
          TARGET: "/opt/junk/"
          EXCLUDE: ""
